baseURL = 'https://laure-cmyk.github.io/labveiltech/'
languageCode = 'fr-ch'
title = 'Blog'
theme = 'shibui'

[params]
  email = "hello@example.com"
  [params.author]
  author = "Laure Mangold"
  

[markup]
  defaultMarkdownHandler = "goldmark"
  # By default, Goldmark trims unsafe outputs which might prevent some shortcodes from rendering.
  # It is recommended to set markup.goldmark.renderer.unsafe=true if you encounter problems.
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = true
    tabWidth = 4
    style = "algol_nu"
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[build]
  writeStats = true

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']

[module]
  [[module.mounts]]
    source = "images"
    target = "static/images"
  [[module.mounts]]
    source = "static"
    target = "static"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
